docs(build): change NodeJS version in BUILD.md to v18.18.2
- Update the NodeJS version in BUILD.md what caused type error in corepack
and prevented yarn from installing packages correctly.
Error message when using node 16: Type Error: URL.canParse is not a function

Co-authored-by: Peter Somogyvari <peter.somogyvari@accenture.com>

Signed-off-by: Tomasz Awramski <tomasz.awramski@fujitsu.com>
Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>