fix: keychain to registry, uuid dep, add back missing gas req parameter
With these changes I was able to build the container image
and then launch it, test it, etc.

The Fabric part of it fails with the error below which I
suspect is a problem with Fabric changing their
release tags over time, breaking software that depends
on Fabric even when exact versions are specified.

},
    data: {
      error: 'Error: PluginLedgerConnectorFabric#transact() Unable to run transaction: Event strategy not satisfied within the timeout period. No response received from event hubs: peer0.org1.example.com, peer0.org2.example.com:9051, peer1.org2.example.com:10051, peer1.org1.example.com:8051\n' +
        '    at PluginLedgerConnectorFabric.transact (/cactus-scratch-1/packages/cactus-plugin-ledger-connector-fabric/dist/lib/main/typescript/plugin-ledger-connector-fabric.js:331:19)\n' +
        '    at runMicrotasks (<anonymous>)\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
    }

Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>